PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Trigrammes(
-- CREATION 15:01 27/04/2021 correspondance nom / trigramme pour convertir les demandeurs de GLPI suivis
    Trg TEXT PRIMARY KEY,
    Nom TEXT NOT NULL
);
INSERT INTO Trigrammes VALUES('GMS','METAIS GILLES');
INSERT INTO Trigrammes VALUES('PCT','COUGOULAT PATRICE');
INSERT INTO Trigrammes VALUES('TSI','SZPAKOWSKI THIERRY');
INSERT INTO Trigrammes VALUES('PMI','MARTINI PATRICK');
INSERT INTO Trigrammes VALUES('LFS','FERNANDEZ LIONEL');
INSERT INTO Trigrammes VALUES('SPE','PODENCE SANDRO');
COMMIT;
